###
### base
###

# Account to work
user_to_work: devel

# domein name
my_domain_name: tacchang.xyz
# host name
my_mailserver_hostname: mail.tacchang.xyz

###
### selfsigned_cert
###
selfsigned_cert:
  cert:
    path: /etc/pki/tls/certs/ssl.crt
  privatekey:
    path: /etc/pki/tls/certs/ssl.pem
  csr:
    path: /etc/pki/tls/certs/ssl.csr

###
### letsencrypt
###
letsencrypt_staging: yes
letsencrypt_renew: yes
letsencrypt_email: "wowtacchang+dti@gmail.com"

###
### postfix
###
postfix_mynetworks: 36.55.229.0/24