###
### base
###

# Account to work
user_to_work: devel

# domein name
base_domain_name: tacchang.xyz
# host name
base_hostname: srv1.tacchang.xyz

###
### letsencrypt
###
letsencrypt_staging: yes
letsencrypt_renew: yes
letsencrypt_email: "wowtacchang+dti@gmail.com"

###
### letsencrypt
###
postfix_mynetworks: 36.55.229.156/32