#
- hosts: test-server
  remote_user: "{{ user_to_work }}"
  become_method: sudo
  vars_files:
    - vars/site.yml
  roles:
    - { role: base, become: yes }
    - { role: users, become: yes }
    - { role: selfsigned_cert, become: yes }
    - { role: mailserver, become: yes }
