- name: Update the /etc/ssh/sshd_config file  (UseDNS)
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^UseDNS"
    line: "UseDNS no"
    insertafter: EOF
    state: present

- name: Update the /etc/ssh/sshd_config file  (GSSAPIAuthentication)
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^GSSAPIAuthentication"
    line: "GSSAPIAuthentication no"
    insertafter: EOF
    state: present
  register: ssh_config

- name: Restart ssh
  service:
    name: sshd
    state: restarted
  when: ssh_config.changed

# DTI VPS(ServerMan)ではhostnamectl set-hostnameができない
#- name: Change hostname
#  hostname: name={{ my_mailserver_hostname }}

- name: 必要なパッケージのインストール
  yum:
    name: "{{ install_packages }}"
    state: present

- name: Disable IPv6
#  shell: echo -e "net.ipv6.conf.all.disable_ipv6 = 1\nnet.ipv6.conf.default.disable_ipv6 = 1" > /etc/sysctl.d/disable_ipv6.conf
#  args:
#    creates: /etc/sysctl.d/disable_ipv6.conf
  template: src="disable_ipv6.conf.j2" dest="/etc/sysctl.d/disable_ipv6.conf"

- name: CommentOut IPv6 row at /etc/hosts
  replace: dest=/etc/hosts regexp='^::1' replace='#::1'

#- name: Disable SELinux on boot
#  lineinfile:
#    dest: /etc/selinux/config
#    regexp: "^SELINUX=.*"
#    line: "SELINUX=disabled"
#    insertafter: EOF
#    state: present

# https://girigiribauer.com/archives/20160906/
- name: SELinux のステータス取得
  shell: getenforce
  register: selinux_status
  changed_when: False
  tags: selinux
  become: True

- name: SELinux をコントロールするためのパッケージ導入
  yum: name=libselinux-python state=installed
  when: selinux_status.stdout == 'Enforcing'
  tags: selinux
  become: True

- name: SELinux の無効化
  selinux: state=disabled
  when: selinux_status.stdout == 'Enforcing'
  tags: selinux
  become: True

- name: SELinux 設定後の再起動
  shell: "sleep 2 && reboot"
  async: 1
  poll: 0
  when: selinux_status.stdout == 'Enforcing'
  tags: selinux
  become: True

- name: SELinux 設定後の再起動完了まで待機
  local_action: wait_for host={{ inventory_hostname }} delay=30
  when: selinux_status.stdout == 'Enforcing'
  tags: selinux
  become: False